# Generated by Django 6.1.1 on 2026-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dclutterd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='business_name',
            new_name='business',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NAIRA'), ('USD', 'US DOLLARS')], default='NGN', max_length=3),
        ),
    ]
