# Generated by Django 6.1.1 on 2026-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dclutterd', '0002_rename_business_name_item_business_item_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='None', max_length=500),
            preserve_default=False,
        ),
    ]
